- hosts: all
  remote_user: root
  gather_facts: yes
  tasks:
  - name: Appliy policy changes
    apply_policy:
      db_id: "{{ db.id }}"
      db_password: "{{ db.password }}"
    register: result
  - debug: var=result
