- hosts: all
  remote_user: root
  gather_facts: yes
  tasks:
  - name: Apply default settings policy
    apply_policy:
      login_id: "{{ web.id }}"
      login_pwd: "{{ web.password }}"
    register: result
  - debug: var=result
