- hosts: all
  remote_user: root
  gather_facts: yes
  tasks:
  - name: Delete IP Blacklist
    blacklist_del:
      db_id: "{{ db.id }}"
      db_password: "{{ db.password }}"
      id: "{{ blacklist_delete.id }}"
    register: result
  - debug: var=result
