- hosts: all
  remote_user: root
  gather_facts: yes
  tasks:
  - name: Delete IP Blacklist
    blacklist_del:
      login_id: "{{ web.id }}"
      login_pwd: "{{ web.password }}"
      rule_id: "{{ blacklist_delete.id }}"
    register: result
  - debug: var=result
