- hosts: all
  remote_user: root
  gather_facts: yes
  tasks:
  - name: Enable IP Blacklist
    blacklist_enable:
      db_id: "{{ db.id }}"
      db_password: "{{ db.password }}"
      id: "{{ blacklist_enable.id }}"
      enable: "{{ blacklist_enable.enable }}"
    register: result
  - debug: var=result
