- hosts: all
  remote_user: root
  gather_facts: yes
  tasks:
  - name: Cancel policy changes
    cancel_policy:
        login_id: "{{ web.id }}"
        login_pwd: "{{ web.password }}"
    register: result
  - debug: var=result
