- hosts: all
  remote_user: root
  gather_facts: yes
  tasks:
  - name: Update pattern through online
    online:
      db_id: "{{ db.id }}"
      db_password: "{{ db.password }}"
    register: result
  - debug: var=result
