- hosts: all
  remote_user: root
  gather_facts: yes
  tasks:
  - name: Update pattern through online
    online:
      login_id: "{{ web.id }}"
      login_pwd: "{{ web.password }}"
    register: result
  - debug: var=result
