- hosts: all
  remote_user: root
  gather_facts: yes
  tasks:
  - name: Set operation mode
    opmode_set:
      login_id: "{{ web.id }}"
      login_pwd: "{{ web.password }}"
      mode: "{{ opmode.mode }}"
    register: result
  - debug: var=result
