- hosts: all
  remote_user: root
  gather_facts: yes
  tasks:
  - name: Enable IP Whitelist
    whitelist_enable:
      login_id: "{{ web.id }}"
      login_pwd: "{{ web.password }}"
      rule_id: "{{ whitelist_enable.id }}"
      enable: "{{ whitelist_enable.enable }}"
    register: result
  - debug: var=result
